// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ickdoazxyioajrgkydii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlja2RvYXp4eWlvYWpyZ2t5ZGlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTEzMTYsImV4cCI6MjA2NTQ2NzMxNn0.NusYeeeEbTH9MfNFKy6h3NIqSmYUtY6V7lZdc8UCSk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);